from concurrent.futures import ThreadPoolExecutor, as_completed
from dedsec.core.colors import Colors
from dedsec.core.utils import append_query_param, error, info, safe_request, section, warn

# WAF vendor signatures keyed by header/cookie/body patterns.
# None as header value means "any value" (presence is enough).
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"cf-ray": None, "cf-cache-status": None, "server": "cloudflare"},
        "cookies": ["cf_clearance", "__cf_bm", "__cflb"],
        "body": ["attention required", "ddos protection by cloudflare", "cloudflare ray id", "enable cookies"],
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": None, "x-amz-cf-id": None, "x-amzn-trace-id": None},
        "cookies": ["aws-waf-token", "awsalb", "awsalbcors"],
        "body": ["aws waf", "request blocked by aws", "403 forbidden"],
    },
    "AWS CloudFront": {
        "headers": {"x-amz-cf-pop": None, "x-amz-cf-id": None},
        "cookies": [],
        "body": ["generated by cloudfront", "request blocked"],
        "_cdn_only": True,
    },
    "Akamai WAF (Kona)": {
        "headers": {"x-akamai-transformed": None, "akamai-origin-hop": None, "x-check-cacheable": None},
        "cookies": ["ak_bmsc", "bm_sv", "bm_sz"],
        "body": ["access denied - akamai", "reference#", "akamai ghost"],
    },
    "Imperva/Incapsula": {
        "headers": {"x-cdn": "incapsula", "x-iinfo": None},
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "body": ["incapsula incident id", "_incapsula_resource"],
    },
    "Sucuri": {
        "headers": {"x-sucuri-id": None, "x-sucuri-cache": None},
        "cookies": [],
        "body": ["sucuri website firewall", "access denied - sucuri", "sucuri cloudproxy"],
    },
    "F5 BIG-IP ASM": {
        "headers": {"x-waf-status": None, "x-cnection": None},
        "cookies": ["bigipserver", "f5_", "ts0", "ts01"],
        "body": ["the requested url was rejected", "f5 networks", "your support id is"],
    },
    "ModSecurity": {
        "headers": {"x-mod-security": None, "x-modsecurity": None},
        "cookies": [],
        "body": ["this error was generated by mod_security", "modsecurity action", "not acceptable"],
    },
    "Barracuda": {
        "headers": {"x-barracuda-connect": None, "x-barracuda-start-time": None},
        "cookies": ["barra_counter_session", "barracuda_"],
        "body": ["barracuda networks", "barracuda web application firewall"],
    },
    "Fortinet FortiWeb": {
        "headers": {"x-waf-event-info": None},
        "cookies": ["fortiwafsid"],
        "body": ["fortiweb", "fortiguard", "fortigate"],
    },
    "Wordfence": {
        "headers": {},
        "cookies": ["wfwaf-authcookie"],
        "body": ["generated by wordfence", "your access to this site has been limited", "wordfence"],
    },
    "Palo Alto": {
        "headers": {"x-pan-waf": None},
        "cookies": [],
        "body": ["palo alto networks", "request denied by pan"],
    },
    "Azure Front Door": {
        "headers": {"x-azure-ref": None, "x-fd-healthprobe": None, "x-ms-ref": None},
        "cookies": [],
        "body": ["our services aren't available", "error 403 - forbidden"],
        "_cdn_only": True,
    },
    "Fastly": {
        "headers": {"x-fastly-request-id": None, "x-served-by": None},
        "cookies": [],
        "body": ["fastly error", "request could not be satisfied"],
        "_cdn_only": True,
    },
    "Radware AppWall": {
        "headers": {"x-rdwr-pop": None},
        "cookies": [],
        "body": ["radware", "appwall"],
    },
    "Wallarm": {
        "headers": {"x-wallarm-node": None},
        "cookies": [],
        "body": ["wallarm", "request blocked by wallarm"],
    },
    "StackPath": {
        "headers": {"x-hw": None, "x-sp-waf": None},
        "cookies": [],
        "body": ["stackpath", "sp-waf"],
    },
    "DataDome": {
        "headers": {"x-datadome": None},
        "cookies": ["datadome"],
        "body": ["datadome", "blocked by datadome"],
    },
    "Kasada": {
        "headers": {"x-kasada-client-hint": None},
        "cookies": ["_kpsdk", "_kp_"],
        "body": ["kasada", "please wait while we verify"],
    },
    "PerimeterX": {
        "headers": {"x-px-cookies": None},
        "cookies": ["_px3", "_pxhd", "_pxde"],
        "body": ["px-captcha", "perimeterx", "access denied - perimeterx"],
    },
    "Reblaze": {
        "headers": {"x-reblaze-protection": None},
        "cookies": ["rbzid"],
        "body": ["reblaze", "access blocked by reblaze"],
    },
    "DenyAll": {
        "headers": {},
        "cookies": ["sessioncookie"],
        "body": ["denyall", "denied by the security policy"],
    },
    "SiteLock": {
        "headers": {"x-sitelock-request-id": None},
        "cookies": ["sitelock_"],
        "body": ["sitelock", "this website is protected by sitelock"],
    },
    "HAProxy": {
        "headers": {"x-haproxy-current-date": None},
        "cookies": [],
        "body": ["400 bad request", "haproxy"],
    },
    "Nginx + Naxsi": {
        "headers": {},
        "cookies": [],
        "body": ["naxsi", "this request has been blocked"],
    },
}

# Headers that signal CDN presence but do NOT by themselves confirm a WAF.
# If a WAF score is driven entirely by these, downgrade to CDN-only label.
CDN_ONLY_HEADERS = {
    "cf-ray", "cf-cache-status",          # Cloudflare CDN (without blocking)
    "x-amz-cf-pop", "x-amz-cf-id",        # CloudFront CDN
    "x-fastly-request-id", "x-served-by", # Fastly CDN
    "x-azure-ref", "x-fd-healthprobe",    # Azure Front Door CDN
}

# Payloads that legitimate WAFs should detect and block.
TRIGGER_PAYLOADS = [
    ("id",     "1' OR '1'='1"),
    ("q",      "<script>alert(1)</script>"),
    ("file",   "../../../../etc/passwd"),
    ("id",     "1 UNION SELECT 1,2,3--"),
    ("cmd",    ";ls -la"),
    ("search", "{{7*7}}"),
    ("input",  "${jndi:ldap://x.x.x.x/a}"),
    ("x",      "' AND SLEEP(5)--"),
    ("q",      "%00"),
    ("path",   "/etc/passwd%00"),
    ("q",      "<img src=x onerror=alert(1)>"),
    ("id",     "1;DROP TABLE users--"),
    ("debug",  "true"),
    ("admin",  "1"),
    ("q",      "OR 1=1"),
]

BLOCKING_STATUSES = {403, 406, 429, 501, 503}


def _lower_headers(headers):
    return {key.lower(): value.lower() for key, value in headers.items()}


def _lower_cookies(resp):
    return [cookie.lower() for cookie in resp.cookies.keys()]


def _is_cdn_only_match(matched_headers):
    """Return True if every matched header is a known CDN-only signal."""
    return all(h in CDN_ONLY_HEADERS for h in matched_headers)


def _score_response(signature, headers_lower, cookies_lower, body_lower, source):
    score = 0
    evidence = []
    matched_headers_this_resp = []

    for header, expected in signature.get("headers", {}).items():
        if header not in headers_lower:
            continue
        value = headers_lower[header]
        if expected is None or expected in value:
            points = 30 if source == "base" else 20
            score += points
            evidence.append(f"{source}: header '{header}' matched")
            matched_headers_this_resp.append(header)

    for cookie in signature.get("cookies", []):
        if any(cookie in candidate for candidate in cookies_lower):
            points = 35 if source == "base" else 25
            score += points
            evidence.append(f"{source}: cookie '{cookie}' matched")

    for pattern in signature.get("body", []):
        if pattern in body_lower:
            points = 20 if source == "base" else 15
            score += points
            evidence.append(f"{source}: body matched '{pattern}'")

    return score, evidence, matched_headers_this_resp


def _request_profiles(responses):
    profiles = []
    for label, response in responses:
        if not response:
            continue
        profiles.append({
            "label": label,
            "status": response.status_code,
            "headers": _lower_headers(response.headers),
            "cookies": _lower_cookies(response),
            "body": response.text.lower(),
            "body_len": len(response.text),
        })
    return profiles


def _response_diff_bonus(base_profile, trigger_profiles):
    """
    Extra confidence points when trigger payloads cause both a blocking status
    AND a significant body-length change vs the base response.
    Returns a dict: waf_name -> bonus_points (applied to all WAFs with evidence).
    """
    base_len = base_profile.get("body_len", 0) if base_profile else 0
    bonus = 0
    for profile in trigger_profiles:
        if profile["status"] in BLOCKING_STATUSES:
            trigger_len = profile.get("body_len", 0)
            if base_len > 0:
                diff_pct = abs(trigger_len - base_len) / base_len
                if diff_pct > 0.20:
                    bonus += 25
                    break  # one strong diff is enough
    return bonus


def run(url, domain, timeout=10):
    section("WAF Detection", "🛡️")
    results = {"detected": [], "confidence": {}, "evidence": {}, "primary": None}

    base_response = safe_request(url, timeout=timeout)
    if not base_response:
        error("Could not connect to target.")
        results["error"] = "Could not connect to target"
        return results

    # Fetch trigger payloads concurrently
    trigger_responses = []

    def _fetch_trigger(param, payload):
        trigger_url = append_query_param(url, param, payload)
        return f"trigger:{param}", safe_request(trigger_url, timeout=timeout, allow_redirects=False)

    with ThreadPoolExecutor(max_workers=min(8, len(TRIGGER_PAYLOADS))) as executor:
        futures = {
            executor.submit(_fetch_trigger, param, payload): (param, payload)
            for param, payload in TRIGGER_PAYLOADS
        }
        for future in as_completed(futures):
            label, resp = future.result()
            trigger_responses.append((label, resp))

    all_responses = [("base", base_response), *trigger_responses]
    response_profiles = _request_profiles(all_responses)

    base_profile = next((p for p in response_profiles if p["label"] == "base"), None)
    trigger_profiles = [p for p in response_profiles if p["label"].startswith("trigger:")]
    blocked_triggers = [p for p in trigger_profiles if p["status"] in BLOCKING_STATUSES]

    # Response-diff bonus (applied to any WAF that has evidence)
    diff_bonus = _response_diff_bonus(base_profile, trigger_profiles)

    scores = {}
    evidence_map = {}
    cdn_only_flags = {}

    for waf_name, signature in WAF_SIGNATURES.items():
        score = 0
        evidence = []
        all_matched_headers = []

        for profile in response_profiles:
            partial_score, partial_evidence, matched_hdrs = _score_response(
                signature,
                profile["headers"],
                profile["cookies"],
                profile["body"],
                source=profile["label"],
            )
            score += partial_score
            evidence.extend(partial_evidence)
            all_matched_headers.extend(matched_hdrs)

        if blocked_triggers and evidence:
            score += 10
            evidence.append(f"trigger behavior: {len(blocked_triggers)} payload(s) returned blocking status")

        # Response-diff bonus
        if diff_bonus and evidence:
            score += diff_bonus
            evidence.append(f"response-diff: body length changed >20% on trigger requests (+{diff_bonus}pts)")

        unique_evidence = list(dict.fromkeys(evidence))
        if score >= 40 and unique_evidence:
            scores[waf_name] = min(score, 100)
            evidence_map[waf_name] = unique_evidence
            # Flag if match is driven purely by CDN-only headers
            if all_matched_headers and _is_cdn_only_match(all_matched_headers):
                cookie_hits = any("cookie" in e for e in unique_evidence)
                body_hits = any("body" in e for e in unique_evidence)
                if not cookie_hits and not body_hits:
                    cdn_only_flags[waf_name] = True

    if not scores:
        if blocked_triggers:
            warn("Blocking behavior observed but no vendor-specific WAF signature matched. Generic WAF/firewall likely present.")
            results["blocked_triggers"] = len(blocked_triggers)
        else:
            warn("No WAF detected or WAF not recognized.")
        return results

    top_waf = max(scores, key=scores.get)
    top_score = scores[top_waf]

    if top_score >= 75:
        confidence = "HIGH"
        conf_color = Colors.RED
    elif top_score >= 50:
        confidence = "MEDIUM"
        conf_color = Colors.YELLOW
    else:
        confidence = "LOW"
        conf_color = Colors.DIM

    display_name = top_waf
    if cdn_only_flags.get(top_waf):
        display_name = f"{top_waf} (CDN detected \u2014 WAF not confirmed)"
        confidence = "LOW"
        conf_color = Colors.DIM
        warn("Score driven by CDN-only headers \u2014 this may be a CDN without WAF. Cookie/body evidence needed to confirm WAF.")

    info("WAF Detected", f"{Colors.BOLD}{display_name}{Colors.RESET}")
    print(
        f"{Colors.GREEN}[+]{Colors.RESET} {Colors.BOLD}Confidence:{Colors.RESET} "
        f"{conf_color}{confidence} ({top_score}%){Colors.RESET}"
    )
    print(f"{Colors.GREEN}[+]{Colors.RESET} {Colors.BOLD}Evidence:{Colors.RESET}")
    for item in evidence_map[top_waf]:
        print(f"       {Colors.DIM}\u2022 {item}{Colors.RESET}")

    if blocked_triggers:
        info("Blocked Trigger Payloads", str(len(blocked_triggers)))

    if len(scores) > 1:
        others = [
            f"{name} ({score}%){' [CDN-only]' if cdn_only_flags.get(name) else ''}"
            for name, score in sorted(scores.items(), key=lambda item: -item[1])
            if name != top_waf
        ]
        warn(f"Also matched: {', '.join(others)}")

    results["detected"] = list(scores.keys())
    results["primary"] = top_waf
    results["confidence"] = {name: f"{score}%" for name, score in scores.items()}
    results["evidence"] = evidence_map
    results["blocked_triggers"] = len(blocked_triggers)
    results["cdn_only_flags"] = list(cdn_only_flags.keys())
    return results
