from dedsec.core.colors import Colors
from dedsec.core.utils import append_query_param, error, info, safe_request, section, warn

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": None, "cf-cache-status": None},
        "cookies": ["cf_clearance", "__cf_bm"],
        "body": ["attention required", "ddos protection by cloudflare", "cloudflare ray id"],
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": None, "x-amz-cf-id": None},
        "cookies": ["aws-waf-token"],
        "body": ["aws waf", "request blocked"],
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": None, "akamai-origin-hop": None},
        "cookies": ["ak_bmsc", "bm_sv", "bm_sz"],
        "body": ["access denied - akamai", "reference#", "akamai ghost"],
    },
    "Imperva/Incapsula": {
        "headers": {"x-cdn": "incapsula", "x-iinfo": None},
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "body": ["incapsula incident id", "_incapsula_resource"],
    },
    "Sucuri": {
        "headers": {"x-sucuri-id": None, "x-sucuri-cache": None},
        "cookies": [],
        "body": ["sucuri website firewall", "access denied - sucuri"],
    },
    "F5 BIG-IP": {
        "headers": {"x-waf-status": None},
        "cookies": ["bigipserver", "f5_", "ts0"],
        "body": ["the requested url was rejected", "f5 networks"],
    },
    "ModSecurity": {
        "headers": {"x-mod-security": None, "x-modsecurity": None},
        "cookies": [],
        "body": ["this error was generated by mod_security", "modsecurity action"],
    },
    "Barracuda": {
        "headers": {"x-barracuda-connect": None},
        "cookies": ["barra_counter_session"],
        "body": ["barracuda networks"],
    },
    "Fortinet/FortiWeb": {
        "headers": {"x-waf-event-info": None},
        "cookies": ["fortiwafsid"],
        "body": ["fortiweb", "fortiguard"],
    },
    "Wordfence": {
        "headers": {},
        "cookies": ["wfwaf-authcookie"],
        "body": ["generated by wordfence", "your access to this site has been limited"],
    },
    "Palo Alto": {
        "headers": {"x-pan-waf": None},
        "cookies": [],
        "body": ["palo alto networks"],
    },
}

TRIGGER_PAYLOADS = [
    ("id", "1' OR '1'='1"),
    ("q", "<script>alert(1)</script>"),
    ("file", "../../../etc/passwd"),
    ("id", "1 UNION SELECT 1,2,3--"),
    ("cmd", ";ls -la"),
]

BLOCKING_STATUSES = {403, 406, 429, 501, 503}


def _lower_headers(headers):
    return {key.lower(): value.lower() for key, value in headers.items()}


def _lower_cookies(resp):
    return [cookie.lower() for cookie in resp.cookies.keys()]


def _score_response(signature, headers_lower, cookies_lower, body_lower, source):
    score = 0
    evidence = []

    for header, expected in signature["headers"].items():
        if header not in headers_lower:
            continue
        value = headers_lower[header]
        if expected is None or expected in value:
            score += 30 if source == "base" else 20
            evidence.append(f"{source}: header '{header}' matched")

    for cookie in signature["cookies"]:
        if any(cookie in candidate for candidate in cookies_lower):
            score += 35 if source == "base" else 25
            evidence.append(f"{source}: cookie '{cookie}' matched")

    for pattern in signature["body"]:
        if pattern in body_lower:
            score += 20 if source == "base" else 15
            evidence.append(f"{source}: body matched '{pattern}'")

    return score, evidence


def _request_profiles(responses):
    profiles = []
    for label, response in responses:
        if not response:
            continue
        profiles.append(
            {
                "label": label,
                "status": response.status_code,
                "headers": _lower_headers(response.headers),
                "cookies": _lower_cookies(response),
                "body": response.text.lower(),
            }
        )
    return profiles


def run(url, domain, timeout=10):
    section("WAF Detection", "🛡️")
    results = {"detected": [], "confidence": {}, "evidence": {}, "primary": None}

    base_response = safe_request(url, timeout=timeout)
    if not base_response:
        error("Could not connect to target.")
        return results

    trigger_responses = []
    for param, payload in TRIGGER_PAYLOADS:
        trigger_url = append_query_param(url, param, payload)
        trigger_responses.append((f"trigger:{param}", safe_request(trigger_url, timeout=timeout, allow_redirects=False)))

    response_profiles = _request_profiles([("base", base_response), *trigger_responses])
    blocked_triggers = [profile for profile in response_profiles if profile["label"].startswith("trigger:") and profile["status"] in BLOCKING_STATUSES]

    scores = {}
    evidence_map = {}

    for waf_name, signature in WAF_SIGNATURES.items():
        score = 0
        evidence = []

        for profile in response_profiles:
            partial_score, partial_evidence = _score_response(
                signature,
                profile["headers"],
                profile["cookies"],
                profile["body"],
                source=profile["label"],
            )
            score += partial_score
            evidence.extend(partial_evidence)

        if blocked_triggers and evidence:
            score += 10
            evidence.append(f"trigger behavior: {len(blocked_triggers)} payload(s) returned blocking status")

        unique_evidence = list(dict.fromkeys(evidence))
        if score >= 40 and unique_evidence:
            scores[waf_name] = min(score, 100)
            evidence_map[waf_name] = unique_evidence

    if not scores:
        if blocked_triggers:
            warn("Blocking behavior observed, but no vendor-specific WAF signature was strong enough to identify the product.")
            results["blocked_triggers"] = len(blocked_triggers)
        else:
            warn("No WAF detected or WAF not recognized.")
        return results

    top_waf = max(scores, key=scores.get)
    top_score = scores[top_waf]

    if top_score >= 75:
        confidence = "HIGH"
        conf_color = Colors.RED
    elif top_score >= 50:
        confidence = "MEDIUM"
        conf_color = Colors.YELLOW
    else:
        confidence = "LOW"
        conf_color = Colors.DIM

    info("WAF Detected", f"{Colors.BOLD}{top_waf}{Colors.RESET}")
    print(
        f"{Colors.GREEN}[+]{Colors.RESET} {Colors.BOLD}Confidence:{Colors.RESET} "
        f"{conf_color}{confidence} ({top_score}%){Colors.RESET}"
    )
    print(f"{Colors.GREEN}[+]{Colors.RESET} {Colors.BOLD}Evidence:{Colors.RESET}")
    for item in evidence_map[top_waf]:
        print(f"       {Colors.DIM}• {item}{Colors.RESET}")

    if len(scores) > 1:
        others = [f"{name} ({score}%)" for name, score in sorted(scores.items(), key=lambda item: -item[1]) if name != top_waf]
        warn(f"Also matched: {', '.join(others)}")

    results["detected"] = list(scores.keys())
    results["primary"] = top_waf
    results["confidence"] = {name: f"{score}%" for name, score in scores.items()}
    results["evidence"] = evidence_map
    results["blocked_triggers"] = len(blocked_triggers)
    return results
