from concurrent.futures import ThreadPoolExecutor, as_completed

from dedsec.core.colors import Colors
from dedsec.core.utils import append_query_param, error, info, safe_request, section, warn

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"cf-ray": None, "cf-cache-status": None, "server": "cloudflare"},
        "cookies": ["cf_clearance", "__cf_bm", "__cflb"],
        "body": ["attention required", "cloudflare ray id"],
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": None, "x-amzn-trace-id": None},
        "cookies": ["aws-waf-token"],
        "body": ["aws waf", "request blocked by aws"],
    },
    "Akamai WAF": {
        "headers": {"x-akamai-transformed": None, "akamai-origin-hop": None},
        "cookies": ["ak_bmsc", "bm_sv", "bm_sz"],
        "body": ["access denied - akamai", "akamai ghost"],
    },
    "Imperva/Incapsula": {
        "headers": {"x-cdn": "incapsula", "x-iinfo": None},
        "cookies": ["visid_incap_", "incap_ses_"],
        "body": ["incapsula incident id"],
    },
    "Sucuri": {
        "headers": {"x-sucuri-id": None, "x-sucuri-cache": None},
        "cookies": [],
        "body": ["sucuri website firewall", "access denied - sucuri"],
    },
    "F5 BIG-IP ASM": {
        "headers": {"x-waf-status": None},
        "cookies": ["bigipserver"],
        "body": ["the requested url was rejected", "your support id is"],
    },
    "ModSecurity": {
        "headers": {"x-mod-security": None, "x-modsecurity": None},
        "cookies": [],
        "body": ["generated by mod_security", "modsecurity action"],
    },
    "Wordfence": {
        "headers": {},
        "cookies": ["wfwaf-authcookie"],
        "body": ["generated by wordfence", "wordfence"],
    },
}

CDN_ONLY_HEADERS = {"cf-ray", "cf-cache-status", "x-amz-cf-id", "x-amz-cf-pop", "x-served-by"}
TRIGGER_PAYLOADS = [
    ("id", "1' OR '1'='1"),
    ("q", "<script>alert(1)</script>"),
    ("file", "../../../../etc/passwd"),
    ("id", "1 UNION SELECT 1,2,3--"),
    ("search", "{{7*7}}"),
    ("q", "OR 1=1"),
]
BLOCKING_STATUSES = {403, 406, 429, 501, 503}


def _profile(label, response):
    if response is None:
        return None
    headers = {key.lower(): str(value).lower() for key, value in response.headers.items()}
    cookies = [str(cookie).lower() for cookie in response.cookies.keys()]
    body = (response.text or "").lower()
    return {
        "label": label,
        "status": response.status_code,
        "headers": headers,
        "cookies": cookies,
        "body": body,
        "body_len": len(body),
    }


def _score(signature, profiles):
    score = 0
    evidence = []
    matched_headers = set()
    for profile in profiles:
        source = profile["label"]
        for header, expected in signature.get("headers", {}).items():
            if header not in profile["headers"]:
                continue
            value = profile["headers"][header]
            if expected is None or expected in value:
                score += 30 if source == "base" else 15
                evidence.append(f"{source}: header '{header}' matched")
                matched_headers.add(header)
        for cookie in signature.get("cookies", []):
            if any(cookie in candidate for candidate in profile["cookies"]):
                score += 35 if source == "base" else 20
                evidence.append(f"{source}: cookie '{cookie}' matched")
        for pattern in signature.get("body", []):
            if pattern in profile["body"]:
                score += 25 if source == "base" else 15
                evidence.append(f"{source}: body matched '{pattern}'")
    return min(score, 100), list(dict.fromkeys(evidence)), matched_headers


def run(url, domain, timeout=10):
    section("WAF Detection", "🛡️")
    results = {
        "detected": [],
        "confidence": {},
        "evidence": {},
        "primary": None,
        "blocked_triggers": 0,
        "tested_triggers": len(TRIGGER_PAYLOADS),
        "transport_failures": 0,
    }

    base_response = safe_request(url, timeout=timeout, cache=False)
    if base_response is None:
        error("Could not connect to target.")
        results["error"] = "Could not connect to target"
        return results

    trigger_responses = []

    def _fetch_trigger(param, payload):
        target = append_query_param(url, param, payload)
        return f"trigger:{param}", safe_request(
            target,
            timeout=timeout,
            allow_redirects=False,
            cache=False,
        )

    with ThreadPoolExecutor(max_workers=min(4, len(TRIGGER_PAYLOADS))) as executor:
        futures = [executor.submit(_fetch_trigger, param, payload) for param, payload in TRIGGER_PAYLOADS]
        for future in as_completed(futures):
            label, response = future.result()
            if response is None:
                results["transport_failures"] += 1
            trigger_responses.append((label, response))

    profiles = []
    for label, response in [("base", base_response)] + trigger_responses:
        item = _profile(label, response)
        if item is not None:
            profiles.append(item)

    trigger_profiles = [item for item in profiles if item["label"].startswith("trigger:")]
    blocked = [item for item in trigger_profiles if item["status"] in BLOCKING_STATUSES]
    results["blocked_triggers"] = len(blocked)

    scored = {}
    for vendor, signature in WAF_SIGNATURES.items():
        score, evidence, matched_headers = _score(signature, profiles)
        if blocked and evidence:
            score = min(100, score + 10)
            evidence.append(f"trigger behavior: {len(blocked)} request(s) returned blocking status")
        if score < 40 or not evidence:
            continue
        only_cdn_headers = (
            matched_headers
            and matched_headers.issubset(CDN_ONLY_HEADERS)
            and not any("cookie" in item or "body" in item for item in evidence)
        )
        scored[vendor] = {
            "score": score,
            "evidence": list(dict.fromkeys(evidence)),
            "cdn_only": only_cdn_headers,
        }

    if not scored:
        if blocked:
            warn(
                "Blocking behavior observed, but no vendor-specific signature matched. "
                "Generic filtering/WAF behavior is possible."
            )
            results["generic_blocking"] = True
        else:
            warn("No recognized WAF signature observed; this does not prove that no WAF exists.")
        return results

    primary = max(scored, key=lambda name: scored[name]["score"])
    primary_data = scored[primary]
    confidence = "HIGH" if primary_data["score"] >= 75 else "MEDIUM" if primary_data["score"] >= 50 else "LOW"
    if primary_data["cdn_only"]:
        confidence = "LOW"
        warn("Primary match is based only on CDN headers; WAF capability is not confirmed.")

    results["primary"] = primary
    results["detected"] = sorted(scored)
    results["confidence"] = {
        vendor: {
            "score": data["score"],
            "level": "LOW" if data["cdn_only"] else (
                "HIGH" if data["score"] >= 75 else "MEDIUM" if data["score"] >= 50 else "LOW"
            ),
            "cdn_only": data["cdn_only"],
        }
        for vendor, data in scored.items()
    }
    results["evidence"] = {vendor: data["evidence"] for vendor, data in scored.items()}

    display = f"{primary} (CDN signal only)" if primary_data["cdn_only"] else primary
    info("Primary Signature", display)
    info("Confidence", f"{confidence} ({primary_data['score']}%)")
    for item in primary_data["evidence"]:
        print(f"       {Colors.DIM}• {item}{Colors.RESET}")
    return results
